datasource:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/user_jdbc_crud
  username: root
  password: root
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true
  context_class: thread
